### ISSUE TITLE
Update to 2.11.1

### ISSUE THREAD

**Issue by TheAifam5** [mesonbuild/catch2#6]
Hey,

Here you can find updated Catch2 to 2.11.1:
https://github.com/TheAifam5/Catch2/tree/2.11.1

I couldn't find a way to merge it here. I would need have access to create a branch here or something.

I needed to change the repository name:
```diff
-catch2
+Catch2
```

Without changing to upper-case, Meson on Linux will create new directory, not inside the Catch2, which will fail.

Example usage:
```
[wrap-file]
directory = Catch2-2.11.1

source_url = https://github.com/catchorg/Catch2/archive/v2.11.1.zip
source_filename = Catch2-2.11.1.zip
source_hash = da97f7acd94ea6e1f26aae4a6edf5d10d020666efaec22781f6ac42371569d2c

patch_url = https://github.com/TheAifam5/Catch2/archive/2.11.1.zip
patch_filename = Catch2-2.11.1-wrap.zip
patch_hash = 8225163fc6640e49beb43059bd8075473f48a3756e44e770ca319820b3180ac0
```

Regards,
TheAifam5

**Comment by legeana** [comment]
I created a branch for 2.11.1. You can also make a pull request against master and I can change it later as needed.
